# Generated by Django 2.0.8 on 2018-09-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swenglish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlist',
            old_name='eng_word',
            new_name='Title',
        ),
    ]
